import { Product } from "./types";

export const products: Product[] = [
  {
    id: "gp-001",
    name: "Gold Nosepin Elegance",
    category: "Gold Nosepins",
    purity: "22K Gold",
    weight: "2.5g",
    price: 18500,
    description: "Handcrafted gold nosepin with intricate floral design, featuring QR authentication for guaranteed purity.",
    details: ["22K Yellow Gold", "Weight: 2.5g", "QR Verified", "Ideal for daily wear", "Comes with authentication certificate"],
    images: [],
    badge: "Best Seller",
    inStock: true,
  },
  {
    id: "gp-002",
    name: "Diamond Gold Ring",
    category: "Gold Rings",
    purity: "18K Gold",
    weight: "6.2g",
    price: 45000,
    originalPrice: 52000,
    description: "Elegant diamond-studded gold ring with a classic solitaire setting, perfect for engagements and special occasions.",
    details: ["18K White Gold", "Diamond: 0.5ct", "Weight: 6.2g", "Hallmarked", "Comes with certificate"],
    images: [],
    badge: "Sale",
    inStock: true,
  },
  {
    id: "gp-003",
    name: "Bridal Gold Necklace",
    category: "Bridal Jewellery",
    purity: "24K Gold",
    weight: "35.0g",
    price: 245000,
    description: "Magnificent bridal gold necklace set with traditional temple-inspired craftsmanship, designed for your special day.",
    details: ["24K Pure Gold", "Weight: 35.0g", "Temple Design", "Matching earrings available", "BIS Hallmarked"],
    images: [],
    badge: "Premium",
    inStock: true,
  },
  {
    id: "gp-004",
    name: "Gold Bangle Set",
    category: "Gold Bangles",
    purity: "22K Gold",
    weight: "28.0g",
    price: 142000,
    description: "Set of two intricately designed gold bangles with matte finish, perfect for festive occasions.",
    details: ["22K Yellow Gold", "Total Weight: 28.0g", "Pair of 2", "Matte finish", "Festival special design"],
    images: [],
    badge: "",
    inStock: true,
  },
  {
    id: "gp-005",
    name: "Temple Earrings",
    category: "Temple Jewellery",
    purity: "22K Gold",
    weight: "12.8g",
    price: 68000,
    description: "Exquisite temple-style gold earrings featuring intricate carving of deities, a timeless heirloom piece.",
    details: ["22K Gold", "Weight: 12.8g", "Temple Design", "Traditional craftsmanship", "Pair"],
    images: [],
    badge: "Handcrafted",
    inStock: true,
  },
  {
    id: "gp-006",
    name: "Daily Wear Chain",
    category: "Daily Wear Collection",
    purity: "18K Gold",
    weight: "8.5g",
    price: 42000,
    description: "Lightweight gold chain designed for everyday elegance, comfortable and durable for daily use.",
    details: ["18K Gold", "Weight: 8.5g", "Length: 18 inches", "Lightweight design", "Lobster clasp"],
    images: [],
    badge: "",
    inStock: true,
  },
  {
    id: "gp-007",
    name: "Gold Earrings Set",
    category: "Gold Earrings",
    purity: "22K Gold",
    weight: "9.2g",
    price: 52000,
    description: "Contemporary gold earrings with a modern design language, perfect for both traditional and western outfits.",
    details: ["22K Gold", "Weight: 9.2g", "Modern design", "Stud style", "Pair"],
    images: [],
    badge: "New",
    inStock: true,
  },
  {
    id: "gp-008",
    name: "Premium Gold Nosepin",
    category: "Gold Nosepins",
    purity: "24K Gold",
    weight: "3.2g",
    price: 24000,
    description: "Premium gold nosepin with a delicate pearl accent, QR verified for authenticity and crafted to perfection.",
    details: ["24K Pure Gold", "Weight: 3.2g", "Pearl accent", "QR Verified", "Gift packaging included"],
    images: [],
    badge: "Limited Edition",
    inStock: true,
  },
  {
    id: "gp-009",
    name: "Gold Necklace Set",
    category: "Gold Necklaces",
    purity: "22K Gold",
    weight: "42.0g",
    price: 289000,
    description: "Opulent gold necklace set with uncut diamond accents, a statement piece for grand celebrations.",
    details: ["22K Gold", "Total Weight: 42.0g", "Uncut diamonds", "Matching earrings included", "Bridal collection"],
    images: [],
    badge: "Premium",
    inStock: true,
  },
  {
    id: "gp-010",
    name: "Gold Ring Classic",
    category: "Gold Rings",
    purity: "22K Gold",
    weight: "4.8g",
    price: 32000,
    description: "Classic gold band ring with a subtle polish finish, an everyday essential for the modern individual.",
    details: ["22K Yellow Gold", "Weight: 4.8g", "Classic design", "Comfort fit", "Hallmarked"],
    images: [],
    badge: "",
    inStock: true,
  },
  {
    id: "gp-011",
    name: "Bridal Gold Bangles",
    category: "Bridal Jewellery",
    purity: "24K Gold",
    weight: "52.0g",
    price: 375000,
    description: "Traditional bridal gold bangles set with intricate kundan work, a treasured heirloom for generations.",
    details: ["24K Pure Gold", "Total Weight: 52.0g", "Kundan work", "Set of 4", "Bridal collection"],
    images: [],
    badge: "Exclusive",
    inStock: true,
  },
  {
    id: "gp-012",
    name: "Gold Nosepin Trio",
    category: "Gold Nosepins",
    purity: "22K Gold",
    weight: "4.0g",
    price: 28000,
    description: "Set of three elegant gold nosepins in different designs, perfect for matching every outfit.",
    details: ["22K Gold", "Total Weight: 4.0g", "Set of 3", "Different designs", "QR Verified"],
    images: [],
    badge: "Value Pack",
    inStock: true,
  },
];

export const categories = [
  { id: "gold-nosepins", name: "Exclusive Gold Nosepins", slug: "gold-nosepins" },
  { id: "bridal-jewellery", name: "Bridal Jewellery", slug: "bridal-jewellery" },
  { id: "gold-necklaces", name: "Gold Necklaces", slug: "gold-necklaces" },
  { id: "gold-rings", name: "Gold Rings", slug: "gold-rings" },
  { id: "gold-bangles", name: "Gold Bangles", slug: "gold-bangles" },
  { id: "gold-earrings", name: "Gold Earrings", slug: "gold-earrings" },
  { id: "temple-jewellery", name: "Temple Jewellery", slug: "temple-jewellery" },
  { id: "daily-wear", name: "Daily Wear Collection", slug: "daily-wear" },
];

export function getProductById(id: string): Product | undefined {
  return products.find((p) => p.id === id);
}

export function getProductsByCategory(category: string): Product[] {
  return products.filter((p) => p.category === category);
}

export function formatPrice(price: number): string {
  return "₹" + price.toLocaleString("en-IN");
}
