import { Product } from "./types";

export const products: Product[] = [
  {
    id: "gp-001",
    name: "Gold Nosepin Elegance",
    category: "Gold Nosepins",
    purity: "22K Gold",
    weight: "2.5g",
    price: 18500,
    description: "Handcrafted gold nosepin with intricate floral design, featuring QR authentication for guaranteed purity.",
    details: ["22K Yellow Gold", "Weight: 2.5g", "QR Verified", "Ideal for daily wear", "Comes with authentication certificate"],
    images: [],
    badge: "Best Seller",
    inStock: true,
  },
  {
    id: "gp-002",
    name: "Diamond Gold Ring",
    category: "Gold Rings",
    purity: "18K Gold",
    weight: "6.2g",
    price: 45000,
    originalPrice: 52000,
    description: "Elegant diamond-studded gold ring with a classic solitaire setting, perfect for engagements and special occasions.",
    details: ["18K White Gold", "Diamond: 0.5ct", "Weight: 6.2g", "Hallmarked", "Comes with certificate"],
    images: [],
    badge: "Sale",
    inStock: true,
  },
  {
    id: "gp-003",
    name: "Bridal Gold Necklace",
    category: "Bridal Jewellery",
    purity: "24K Gold",
    weight: "35.0g",
    price: 245000,
    description: "Magnificent bridal gold necklace set with traditional temple-inspired craftsmanship, designed for your special day.",
    details: ["24K Pure Gold", "Weight: 35.0g", "Temple Design", "Matching earrings available", "BIS Hallmarked"],
    images: [],
    badge: "Premium",
    inStock: true,
  },
  {
    id: "gp-004",
    name: "Gold Bangle Set",
    category: "Gold Bangles",
    purity: "22K Gold",
    weight: "28.0g",
    price: 142000,
    description: "Set of two intricately designed gold bangles with matte finish, perfect for festive occasions.",
    details: ["22K Yellow Gold", "Total Weight: 28.0g", "Pair of 2", "Matte finish", "Festival special design"],
    images: [],
    badge: "",
    inStock: true,
  },
  {
    id: "gp-005",
    name: "Temple Earrings",
    category: "Temple Jewellery",
    purity: "22K Gold",
    weight: "12.8g",
    price: 68000,
    description: "Exquisite temple-style gold earrings featuring intricate carving of deities, a timeless heirloom piece.",
    details: ["22K Gold", "Weight: 12.8g", "Temple Design", "Traditional craftsmanship", "Pair"],
    images: [],
    badge: "Handcrafted",
    inStock: true,
  },
  {
    id: "gp-006",
    name: "Daily Wear Chain",
    category: "Daily Wear Collection",
    purity: "18K Gold",
    weight: "8.5g",
    price: 42000,
    description: "Lightweight gold chain designed for everyday elegance, comfortable and durable for daily use.",
    details: ["18K Gold", "Weight: 8.5g", "Length: 18 inches", "Lightweight design", "Lobster clasp"],
    images: [],
    badge: "",
    inStock: true,
  },
  {
    id: "gp-007",
    name: "Gold Earrings Set",
    category: "Gold Earrings",
    purity: "22K Gold",
    weight: "9.2g",
    price: 52000,
    description: "Contemporary gold earrings with a modern design language, perfect for both traditional and western outfits.",
    details: ["22K Gold", "Weight: 9.2g", "Modern design", "Stud style", "Pair"],
    images: [],
    badge: "New",
    inStock: true,
  },
  {
    id: "gp-008",
    name: "Premium Gold Nosepin",
    category: "Gold Nosepins",
    purity: "24K Gold",
    weight: "3.2g",
    price: 24000,
    description: "Premium gold nosepin with a delicate pearl accent, QR verified for authenticity and crafted to perfection.",
    details: ["24K Pure Gold", "Weight: 3.2g", "Pearl accent", "QR Verified", "Gift packaging included"],
    images: [],
    badge: "Limited Edition",
    inStock: true,
  },
  {
    id: "gp-009",
    name: "Gold Necklace Set",
    category: "Gold Necklaces",
    purity: "22K Gold",
    weight: "42.0g",
    price: 289000,
    description: "Opulent gold necklace set with uncut diamond accents, a statement piece for grand celebrations.",
    details: ["22K Gold", "Total Weight: 42.0g", "Uncut diamonds", "Matching earrings included", "Bridal collection"],
    images: [],
    badge: "Premium",
    inStock: true,
  },
  {
    id: "gp-010",
    name: "Gold Ring Classic",
    category: "Gold Rings",
    purity: "22K Gold",
    weight: "4.8g",
    price: 32000,
    description: "Classic gold band ring with a subtle polish finish, an everyday essential for the modern individual.",
    details: ["22K Yellow Gold", "Weight: 4.8g", "Classic design", "Comfort fit", "Hallmarked"],
    images: [],
    badge: "",
    inStock: true,
  },
  {
    id: "gp-011",
    name: "Bridal Gold Bangles",
    category: "Bridal Jewellery",
    purity: "24K Gold",
    weight: "52.0g",
    price: 375000,
    description: "Traditional bridal gold bangles set with intricate kundan work, a treasured heirloom for generations.",
    details: ["24K Pure Gold", "Total Weight: 52.0g", "Kundan work", "Set of 4", "Bridal collection"],
    images: [],
    badge: "Exclusive",
    inStock: true,
  },
  {
    id: "gp-012",
    name: "Gold Nosepin Trio",
    category: "Gold Nosepins",
    purity: "22K Gold",
    weight: "4.0g",
    price: 28000,
    description: "Set of three elegant gold nosepins in different designs, perfect for matching every outfit.",
    details: ["22K Gold", "Total Weight: 4.0g", "Set of 3", "Different designs", "QR Verified"],
    images: [],
    badge: "Value Pack",
    inStock: true,
  },
  {
    id: "gp-013",
    name: "Gold Nosepin with Pearl",
    category: "Gold Nosepins",
    purity: "22K Gold",
    weight: "2.8g",
    price: 21000,
    description: "Elegant gold nosepin adorned with a freshwater pearl, designed for both daily wear and special occasions.",
    details: ["22K Gold", "Weight: 2.8g", "Freshwater pearl", "QR Verified", "Hypoallergenic"],
    images: [],
    badge: "",
    inStock: true,
  },
  {
    id: "gp-014",
    name: "Diamond Gold Nosepin",
    category: "Gold Nosepins",
    purity: "18K Gold",
    weight: "3.0g",
    price: 35000,
    description: "Stunning gold nosepin with a微小 diamond accent, combining modern style with traditional grace.",
    details: ["18K Gold", "Weight: 3.0g", "Diamond: 0.1ct", "QR Verified", "Comes with certificate"],
    images: [],
    badge: "New",
    inStock: true,
  },
  {
    id: "gp-015",
    name: "Gold Necklace Chain",
    category: "Gold Necklaces",
    purity: "22K Gold",
    weight: "18.5g",
    price: 98000,
    description: "Classic gold chain necklace with a refined finish, versatile enough for daily wear or layering.",
    details: ["22K Gold", "Weight: 18.5g", "Length: 20 inches", "Classic link design", "Secure lobster clasp"],
    images: [],
    badge: "",
    inStock: true,
  },
  {
    id: "gp-016",
    name: "Gold Mangalsutra Necklace",
    category: "Gold Necklaces",
    purity: "24K Gold",
    weight: "24.0g",
    price: 156000,
    description: "Traditional gold mangalsutra necklace with black bead accents, an essential piece for every married woman.",
    details: ["24K Gold", "Weight: 24.0g", "Black bead accents", "Traditional design", "Adjustable length"],
    images: [],
    badge: "Traditional",
    inStock: true,
  },
  {
    id: "gp-017",
    name: "Gold Chain with Pendant",
    category: "Gold Necklaces",
    purity: "22K Gold",
    weight: "15.0g",
    price: 85000,
    description: "Elegant gold chain with a beautifully crafted Lakshmi pendant, perfect for festive occasions.",
    details: ["22K Gold", "Total Weight: 15.0g", "Lakshmi pendant", "Chain: 18 inches", "Ideal for festivals"],
    images: [],
    badge: "Festival Special",
    inStock: true,
  },
  {
    id: "gp-018",
    name: "Gold Ring with Ruby",
    category: "Gold Rings",
    purity: "22K Gold",
    weight: "5.6g",
    price: 38000,
    description: "Stunning gold ring set with a natural ruby gemstone, combining vibrant color with timeless gold.",
    details: ["22K Gold", "Weight: 5.6g", "Ruby: 0.8ct", "Hallmarked", "Adjustable size"],
    images: [],
    badge: "",
    inStock: true,
  },
  {
    id: "gp-019",
    name: "Gold Couple Ring Set",
    category: "Gold Rings",
    purity: "18K Gold",
    weight: "8.0g",
    price: 55000,
    description: "Matching couple gold ring set with minimalist design, perfect for engagements and anniversaries.",
    details: ["18K Gold", "Total Weight: 8.0g (pair)", "Pair of 2", "Minimalist design", "Comes in gift box"],
    images: [],
    badge: "Best Seller",
    inStock: true,
  },
  {
    id: "gp-020",
    name: "Gold Earrings Jhumka",
    category: "Gold Earrings",
    purity: "22K Gold",
    weight: "14.5g",
    price: 72000,
    description: "Traditional gold jhumka earrings with intricate filigree work, a timeless addition to any jewelry collection.",
    details: ["22K Gold", "Total Weight: 14.5g", "Traditional jhumka style", "Filigree work", "Pair"],
    images: [],
    badge: "Handcrafted",
    inStock: true,
  },
  {
    id: "gp-021",
    name: "Gold Stud Earrings",
    category: "Gold Earrings",
    purity: "22K Gold",
    weight: "6.5g",
    price: 35000,
    description: "Simple yet elegant gold stud earrings with a polished finish, perfect for everyday sophistication.",
    details: ["22K Gold", "Weight: 6.5g", "Stud style", "Polished finish", "Pair"],
    images: [],
    badge: "",
    inStock: true,
  },
  {
    id: "gp-022",
    name: "Gold Drop Earrings",
    category: "Gold Earrings",
    purity: "24K Gold",
    weight: "11.0g",
    price: 62000,
    description: "Graceful gold drop earrings with a delicate chain detail, adding a touch of elegance to any outfit.",
    details: ["24K Gold", "Weight: 11.0g", "Drop style", "Chain detail", "Pair"],
    images: [],
    badge: "New",
    inStock: true,
  },
  {
    id: "gp-023",
    name: "Gold Bangle with Red Accent",
    category: "Gold Bangles",
    purity: "22K Gold",
    weight: "16.5g",
    price: 88000,
    description: "Beautiful gold bangle with enamel red accents, a festive favorite that complements any traditional attire.",
    details: ["22K Gold", "Weight: 16.5g", "Enamel red accents", "Adjustable", "Festival design"],
    images: [],
    badge: "Festival Special",
    inStock: true,
  },
  {
    id: "gp-024",
    name: "Gold Slim Bangle",
    category: "Gold Bangles",
    purity: "22K Gold",
    weight: "12.0g",
    price: 65000,
    description: "Sleek slim gold bangle with a modern matte finish, designed for the contemporary woman.",
    details: ["22K Gold", "Weight: 12.0g", "Slim design", "Matte finish", "Comfort fit"],
    images: [],
    badge: "",
    inStock: true,
  },
  {
    id: "gp-025",
    name: "Gold Broad Bangle",
    category: "Gold Bangles",
    purity: "24K Gold",
    weight: "32.0g",
    price: 195000,
    description: "Statement gold broad bangle with intricate carvings, a bold piece for grand celebrations.",
    details: ["24K Gold", "Weight: 32.0g", "Broad design", "Intricate carvings", "Bridal collection"],
    images: [],
    badge: "Premium",
    inStock: true,
  },
  {
    id: "gp-026",
    name: "Bridal Gold Earring Set",
    category: "Bridal Jewellery",
    purity: "24K Gold",
    weight: "22.0g",
    price: 175000,
    description: "Exquisite bridal gold earring set with kundan and polki work, designed to make you shine on your special day.",
    details: ["24K Gold", "Weight: 22.0g", "Kundan & polki work", "Bridal design", "Pair with screw back"],
    images: [],
    badge: "Exclusive",
    inStock: true,
  },
  {
    id: "gp-027",
    name: "Bridal Gold Mang tikka",
    category: "Bridal Jewellery",
    purity: "22K Gold",
    weight: "18.0g",
    price: 125000,
    description: "Traditional gold mang tikka with pearl drops, an essential bridal accessory that completes the wedding look.",
    details: ["22K Gold", "Weight: 18.0g", "Pearl drops", "Traditional design", "Adjustable chain"],
    images: [],
    badge: "Handcrafted",
    inStock: true,
  },
  {
    id: "gp-028",
    name: "Gold Bridal Nose Ring",
    category: "Bridal Jewellery",
    purity: "24K Gold",
    weight: "5.0g",
    price: 38000,
    description: "Premium bridal gold nose ring with chain, a statement piece for the wedding day and beyond.",
    details: ["24K Gold", "Weight: 5.0g", "With chain", "Bridal design", "QR Verified"],
    images: [],
    badge: "Limited Edition",
    inStock: true,
  },
];

export const categories = [
  { id: "gold-nosepins", name: "Gold Nosepins", slug: "gold-nosepins", count: 5 },
  { id: "bridal-jewellery", name: "Bridal Jewellery", slug: "bridal-jewellery", count: 5 },
  { id: "gold-necklaces", name: "Gold Necklaces", slug: "gold-necklaces", count: 4 },
  { id: "gold-rings", name: "Gold Rings", slug: "gold-rings", count: 4 },
  { id: "gold-bangles", name: "Gold Bangles", slug: "gold-bangles", count: 4 },
  { id: "gold-earrings", name: "Gold Earrings", slug: "gold-earrings", count: 4 },
  { id: "temple-jewellery", name: "Temple Jewellery", slug: "temple-jewellery", count: 1 },
  { id: "daily-wear", name: "Daily Wear", slug: "daily-wear", count: 1 },
];

export const categorySlugToName: Record<string, string> = {
  "gold-nosepins": "Gold Nosepins",
  "bridal-jewellery": "Bridal Jewellery",
  "gold-necklaces": "Gold Necklaces",
  "gold-rings": "Gold Rings",
  "gold-bangles": "Gold Bangles",
  "gold-earrings": "Gold Earrings",
  "temple-jewellery": "Temple Jewellery",
  "daily-wear": "Daily Wear",
};

export function getProductById(id: string): Product | undefined {
  return products.find((p) => p.id === id);
}

export function getProductsByCategory(category: string): Product[] {
  return products.filter((p) => p.category === category);
}

export function getCategoryName(slug: string): string {
  return categorySlugToName[slug] || slug;
}

export function getCategorySlug(name: string): string {
  return Object.entries(categorySlugToName).find(([, v]) => v === name)?.[0] || name.toLowerCase().replace(/\s+/g, "-");
}

export function formatPrice(price: number): string {
  return "₹" + price.toLocaleString("en-IN");
}
